repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      exclude: data.py|settings.py|snapshots/
      language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      exclude: data.py|settings.py|migrations/|snapshots/
