repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      exclude: data.py|settings.py|snapshots/
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      exclude: data.py|settings.py|migrations/|snapshots/
